name: Trigger Autograding

'on':
  push:
    paths:
      - 'student_assignment.py'

jobs:
  trigger-autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Autograding
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type": "autograde", "client_payload": { "repo": "${{ github.repository }}", "commit_sha": "${{ github.sha }}" }}' \
            https://api.github.com/repos/IcensRAGHomework/autograder-demo/actions/workflows/autograde.yml/dispatches
